<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RuntimeIdentifiers>win-x64;osx-x64</RuntimeIdentifiers>
    <LangVersion>latest</LangVersion>
    <RootNamespace>sttz.InstallUnity</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Label="Package">
    <Version>2.13.2</Version>
    <Authors>Adrian Stutz (sttz.ch)</Authors>
    <Product>install-unity</Product>
    <Description>install-unity unofficial Unity installer library</Description>
    <Copyright>Copyright © Adrian Stutz. All rights Reserved</Copyright>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/sttz/install-unity</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>Unity;Installer</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ini-parser" Version="3.4.0" NoWarn="NU1701" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="plist-cil" Version="2.3.1" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

</Project>
